<a href="https://colab.research.google.com/github/Reshmykris/Day-1_DS_ML/blob/main/Day1_DS_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Implementing Numpy using python programming

In [ ]:
#importing libaries

In [ ]:
import numpy as np

a = [1,2,3,4]  #list1
arr1 = np.array(a)
print(arr1)


b = [[1,2,3,4], [6,7,8,9]]   # list2

arr2 = np.array(b)
print(arr2)


[1 2 3 4]
[[1 2 3 4]
 [6 7 8 9]]


In [ ]:
import numpy as np
import sys
s =np.range(1000)
print("Size of each elt np arr in bytes", s.itemsize)
print("Size of whole arr in bytes", s.size*s.itemsize)



AttributeError: ignored

In [ ]:
import numpy as np
import time
a = range(10000)
b = range(10000)

start = time.time() #mark the start time

# List comprehension (multiply each elt of a & b)

ab = [(a*b) for a,b in zip(a,b)]

end=time.time() #mark the end time

print("tot time taken:", end-start)



tot time taken: 0.0029532909393310547


In [ ]:
import numpy as np

arr3 = np.array([[1,2,3], [3,6,9]], ndmin=2) #2D np array

print(arr3)

[[1 2 3]
 [3 6 9]]


In [ ]:
arr4 = np.array([[1,2,3,], [4,5,6]])
print(arr4.dtype)
print(arr4.ndim)
print(arr4.shape)
print(arr4.size)

int64
2
(2, 3)
6


In [ ]:
z = np.zeros((2,4))
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
import numpy as np
c = np.arange(3,10,2)   #if range() throws error, use arange()
print(c)
print(type(c))

[3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:
a = [1,2,3,4]
b=np.array(a)
print(b)

[1 2 3 4]


In [ ]:
#slicing - Creating substrings from the main string

#indexing - Getting the value from a specific index position, or from lower range to upper range

#range(lower, Upper+1) - 0-10 mention as(0,11)

print(b[3])

b[5]


4


IndexError: ignored

In [ ]:
b[2]

3

In [ ]:
b[-1]   #negative indexing - reverse order -1 to n

4

In [ ]:
b[1:2]

array([2])

In [ ]:
print(b[0:2])  # upper bound + 1


[1 2]


In [ ]:
b[1:3] #print elts from 1st to 2nd elt

array([2, 3])

In [ ]:
b[3] =10 #updating the values
print(b)

[ 1  2  3 10]


In [ ]:
print(b[2:]) #printing elts from 2nd index to last


[ 3 10]


In [ ]:
print(b[:2])

[1 2]


In [ ]:
c=np.array([[1,2,3,4,5], 
            [6,7,8,9,10]])

print(c[1])

[ 6  7  8  9 10]


In [ ]:
print(c[0])

[1 2 3 4 5]


In [ ]:
print(c[1][3])

9



## *Pandas Library Impl

In [ ]:
#pandas is ##https://github.com/TVMSairam123  youtube - Tech 'N' Life
## linkedInSairam Tadepalli


import pandas as pd

